import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const appSource = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
const layoutSource = await readFile(new URL("../src/components/Layout.tsx", import.meta.url), "utf8");
const pageSource = await readFile(new URL("../src/pages/DemoTrade.tsx", import.meta.url), "utf8");
const stylesSource = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
const persistenceSource = await readFile(new URL("../src/lib/demoTradePersistence.ts", import.meta.url), "utf8");
const reconciliationSource = await readFile(new URL("../src/lib/demoTradeReconciliation.ts", import.meta.url), "utf8");
const marketDataSource = await readFile(new URL("../src/lib/demoTradeMarketData.ts", import.meta.url), "utf8");
const reconcileFunctionSource = await readFile(new URL("../supabase/functions/demo-trade-reconcile/index.ts", import.meta.url), "utf8");
const migrationSource = await readFile(new URL("../supabase/migrations/202606160001_demo_trade.sql", import.meta.url), "utf8");
const grantMigrationSource = await readFile(new URL("../supabase/migrations/202606180001_demo_trade_persistence_grants.sql", import.meta.url), "utf8");
const staleSaveMigrationSource = await readFile(new URL("../supabase/migrations/202606180002_demo_trade_stale_save_guard.sql", import.meta.url), "utf8");
const serverReconciliationMigrationSource = await readFile(new URL("../supabase/migrations/202606180003_demo_trade_server_reconciliation.sql", import.meta.url), "utf8");

test("Demo Trade page renders as a public route", () => {
  assert.match(appSource, /import \{ DemoTrade \} from "\.\/pages\/DemoTrade"/);
  assert.match(appSource, /path="demo-trade" element=\{<DemoTrade \/>\}/);
  assert.doesNotMatch(appSource, /path="demo-trade"[\s\S]{0,120}ProtectedRoute/);
});

test("header contains Demo Trade link for all users", () => {
  assert.match(layoutSource, /to: "\/demo-trade", label: "Demo Trade"/);
  assert.match(layoutSource, /ChartCandlestick/);
});

test("Demo Trade page includes guest and authenticated persistence paths", () => {
  assert.match(pageSource, /loadGuestDemoTradeState/);
  assert.match(pageSource, /saveGuestDemoTradeState/);
  assert.match(pageSource, /loadRegisteredDemoTradeState/);
  assert.match(pageSource, /saveRegisteredDemoTradeState/);
  assert.match(persistenceSource, /window\.sessionStorage/);
  assert.match(persistenceSource, /window\.localStorage/);
  assert.match(persistenceSource, /registeredStateKey/);
  assert.match(persistenceSource, /chooseLatestState/);
  assert.match(persistenceSource, /demo_trade_states/);
  assert.match(persistenceSource, /save_demo_trade_state/);
  assert.match(persistenceSource, /demo-trade-reconcile/);
  assert.match(persistenceSource, /RegisteredDemoTradeLoadResult/);
  assert.match(persistenceSource, /isAccountSyncAvailable/);
  assert.match(persistenceSource, /mergeBracketOrdersForSameOpenPosition/);
  assert.match(persistenceSource, /normalizeStoredOpenPosition/);
  assert.match(persistenceSource, /REGISTERED_SAVE_ERROR_MESSAGE/);
  assert.match(persistenceSource, /onConflict: "user_id"/);
  assert.match(persistenceSource, /throw new Error\(REGISTERED_SAVE_ERROR_MESSAGE\)/);
  assert.match(pageSource, /DEMO_TRADE_LOAD_ERROR_MESSAGE/);
  assert.match(pageSource, /persistenceError/);
  assert.match(pageSource, /setIsHydrated\(false\)/);
  assert.match(pageSource, /setIsHydrated\(isAccountSyncAvailable\)/);
  assert.match(pageSource, /Demo trade progress could not be saved to your account/);
});

test("registered Demo Trade has backend reconciliation primitives", () => {
  assert.match(reconciliationSource, /reconcileDemoTradeStateWithCandles/);
  assert.match(reconciliationSource, /liquidation first, then stop loss, then take profits/);
  assert.match(reconcileFunctionSource, /fetchHistoricalCandles/);
  assert.match(reconcileFunctionSource, /save_reconciled_demo_trade_state/);
  assert.match(reconcileFunctionSource, /scope === "all"/);
  assert.match(serverReconciliationMigrationSource, /demo_trade_execution_events/);
  assert.match(serverReconciliationMigrationSource, /unique \(user_id, trade_id, event_key\)/);
  assert.match(serverReconciliationMigrationSource, /for update/);
  assert.match(serverReconciliationMigrationSource, /cron\.schedule/);
  assert.match(serverReconciliationMigrationSource, /demo-trade-reconcile-every-5-minutes/);
});

test("Demo Trade does not account-save ordinary market ticks over bracket edits", () => {
  assert.match(pageSource, /pendingMarketStateToPersistRef/);
  assert.match(pageSource, /shouldPersistMarketState/);
  assert.match(pageSource, /applyMarketPriceToDemoState/);
  assert.match(pageSource, /persistDemoState\(pendingMarketState\)/);
  assert.doesNotMatch(pageSource, /window\.setTimeout\(\(\) => \{\s*const save = user/);
});

test("Demo Trade page includes custom chart and no TradingView widget", () => {
  assert.match(pageSource, /function DemoTradeChart/);
  assert.match(pageSource, /chartClassName/);
  assert.match(pageSource, /buildOverlayLines/);
  assert.doesNotMatch(pageSource, /TradingViewChart|tradingview-widget|s3\.tradingview/);
});

test("Demo Trade chart has timeframe tabs, right price scale, and compact controls", () => {
  assert.match(pageSource, /demoTradeTimeframes\.map/);
  assert.doesNotMatch(marketDataSource, /\{ value: "1m", label: "1m" \}/);
  assert.match(pageSource, /chart-axis-panel/);
  assert.match(pageSource, /chart-price-label/);
  assert.match(pageSource, /onContextMenu=\{\(event\) => event\.preventDefault\(\)\}/);
  assert.match(pageSource, /onPointerDown=\{startRightDrag\}/);
  assert.match(pageSource, /onLostPointerCapture=\{stopRightDrag\}/);
  assert.match(pageSource, /dragStartRef\.current \|\| priceScaleStartRef\.current\) return/);
  assert.match(pageSource, /setPointerCapture/);
  assert.match(pageSource, /event\.clientX - dragStartRef\.current\.x/);
  assert.match(pageSource, /futurePaddingCandles/);
  assert.match(pageSource, /pricePan/);
  assert.match(pageSource, /visiblePriceRange/);
  assert.match(pageSource, /setPricePan\(dragStartRef\.current\.pricePan \+ deltaY \* pricePerPixel\)/);
  assert.match(pageSource, /priceScaleStartRef/);
  assert.match(pageSource, /crosshair/);
  assert.match(pageSource, /updateCrosshair/);
  assert.match(pageSource, /getSvgPointer/);
  assert.match(pageSource, /chart-crosshair-price/);
  assert.match(pageSource, /line\.tone !== "liquidation"/);
  assert.match(pageSource, /label: "Entry", price: position\.entryPrice/);
  assert.match(pageSource, /subscribeDemoTradePriceStream/);
  assert.match(pageSource, /applyLiveTicker/);
  assert.match(pageSource, /getCandleBucketStart/);
  assert.match(pageSource, /startRightDrag/);
  assert.match(pageSource, /ZoomIn/);
  assert.match(pageSource, /ZoomOut/);
  assert.match(pageSource, /isBullishCandle/);
  assert.match(pageSource, /latestCandleTone/);
  assert.match(pageSource, /resolveOverlayMarkerLayouts/);
  assert.match(pageSource, /resolveOverlayMarkerCluster/);
  assert.match(pageSource, /chart-marker-connector/);
  assert.match(pageSource, /isOverlayPriceMarker/);
  assert.match(pageSource, /chart-price-marker-label/);
  assert.match(stylesSource, /chart-marker-connector/);
  assert.match(stylesSource, /trade-overlay-line\.mark line:not\(\.chart-marker-connector\)/);
  assert.match(stylesSource, /stroke-dasharray: 1 7/);
  assert.match(stylesSource, /trade-overlay-line\.mark\.up \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.mark\.down \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.entry \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.target \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.danger \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.liquidation \.chart-price-marker/);
  assert.match(stylesSource, /aspect-ratio: 1/);
  assert.match(pageSource, /DEMO_TRADE_LIVE_REFRESH_MS = 1000/);
  assert.match(pageSource, /DEMO_TRADE_CANDLE_SYNC_MS = 10000/);
  assert.match(pageSource, /applyLivePriceToCandles/);
  assert.match(pageSource, /buildCandleShape/);
  assert.match(pageSource, /minWickHeight/);
  assert.doesNotMatch(pageSource, /clampPricePan|minPricePan|maxPricePan|clampedPricePan/);
  assert.doesNotMatch(pageSource, /chartTop|chartBottom/);
  assert.match(marketDataSource, /"6h"/);
  assert.match(marketDataSource, /"12h"/);
  assert.match(marketDataSource, /"1M"/);
  assert.doesNotMatch(pageSource, /Zoom In|Zoom Out|Pan Left|Pan Right/);
  assert.doesNotMatch(pageSource, /ArrowLeft|ArrowRight/);
});

test("Demo Trade page includes trade ticket, management, CSV export, and reset modal", () => {
  assert.match(pageSource, /function TradeEntryForm/);
  assert.match(pageSource, /futures-ticket/);
  assert.match(stylesSource, /align-items: stretch/);
  assert.match(stylesSource, /demo-ticket-panel[\s\S]*align-self: stretch/);
  assert.match(pageSource, /type DemoQuantityUnit = "usdt" \| "btc" \| "cont"/);
  assert.match(pageSource, /function QuantityUnitSelector/);
  assert.match(pageSource, /ORDER BY QUANTITY/);
  assert.match(pageSource, /aria-label="Set quantity unit"/);
  assert.match(pageSource, /onQuantityUnitChange=\{applyQuantityUnit\}/);
  assert.match(pageSource, /quantityUnitLabels/);
  assert.match(pageSource, /DEMO_CONTRACT_BTC_SIZE = 0\.0001/);
  assert.match(pageSource, /quantityInputToNotional/);
  assert.match(pageSource, /notionalToQuantityInput/);
  assert.match(pageSource, /convertQuantityInput/);
  assert.match(pageSource, /quantityUnit=\{quantityUnit\}/);
  assert.match(pageSource, /placeDemoLimitOrder/);
  assert.match(pageSource, /quantityInputToNotional\(amountValue, quantityUnit, nextLimitPrice\)/);
  assert.match(pageSource, /Quantity \(\{unitLabel\}\)/);
  assert.match(stylesSource, /unit-popover/);
  assert.match(stylesSource, /unit-option-grid/);
  assert.match(stylesSource, /futures-quantity-label/);
  assert.doesNotMatch(pageSource, /Futures Unit Settings|showQuantityUnitModal|draftQuantityUnit/);
  assert.doesNotMatch(stylesSource, /futures-unit-modal/);
  assert.match(pageSource, /BTCUSDT Perpetual/);
  assert.match(pageSource, /Limit orders are available for registered users only/);
  assert.match(pageSource, /Limit Price/);
  assert.match(pageSource, /marginMode/);
  assert.match(pageSource, /Margin mode/);
  assert.match(pageSource, /function LeverageSelector/);
  assert.match(pageSource, /SET LEVERAGE/);
  assert.match(pageSource, /aria-label="Set leverage"/);
  assert.match(pageSource, /aria-label="Decrease leverage"/);
  assert.match(pageSource, /aria-label="Increase leverage"/);
  assert.match(pageSource, /aria-label="Leverage slider"/);
  assert.match(pageSource, /onApply\(String\(nextLeverage\)\)/);
  assert.match(stylesSource, /leverage-popover/);
  assert.match(stylesSource, /leverage-stepper/);
  assert.doesNotMatch(pageSource, /select className="futures-mode-chip" value=\{leverage\}/);
  assert.match(pageSource, /Cross/);
  assert.match(pageSource, /liquidationCollateral/);
  assert.match(pageSource, /isBracketEnabled/);
  assert.match(pageSource, /stopLoss: 0/);
  assert.match(pageSource, /floorTo/);
  assert.match(pageSource, /Position size percent/);
  assert.match(pageSource, /percentSliderStyle/);
  assert.match(stylesSource, /--slider-thumb-center/);
  assert.match(stylesSource, /--slider-quarter-offset/);
  assert.match(stylesSource, /futures-percent-marks span:nth-child\(4\)/);
  assert.match(pageSource, /Long Liquidation Price/);
  assert.match(pageSource, /Open Long/);
  assert.match(pageSource, /Open Short/);
  assert.match(pageSource, /primary-button futures-submit long candle-hover-button/);
  assert.match(pageSource, /primary-button futures-submit short candle-hover-button/);
  assert.match(pageSource, /data-hover-chart-tone="success"/);
  assert.match(pageSource, /data-hover-chart-tone="danger"/);
  assert.match(stylesSource, /candle-hover-button:hover:not\(:disabled\)/);
  assert.match(stylesSource, /hover-chart-size, min\(280px, calc\(100% - 8px\)\) calc\(100% - 8px\)/);
  assert.match(stylesSource, /var\(--hover-chart-overlay, var\(--btc-chart-overlay\)\)/);
  assert.match(stylesSource, /primary-button:not\(\.compact\):not\(\.candle-hover-button\):hover/);
  assert.doesNotMatch(pageSource, /Chase Limit/);
  assert.doesNotMatch(pageSource, /Position Size/);
  assert.doesNotMatch(pageSource, />S<\/span>/);
  assert.doesNotMatch(pageSource, /futures-direction-toggle/);
  assert.doesNotMatch(pageSource, /Refresh BTC/);
  assert.doesNotMatch(pageSource, /Data \/ Save/);
  assert.doesNotMatch(pageSource, /Saving\.\.\.|Ready/);
  assert.doesNotMatch(pageSource, /Trigger Price|pendingTriggerOrder|isTriggerPriceReached/);
  assert.match(pageSource, /function PositionManager/);
  assert.match(pageSource, /function CurrentPositionPanel/);
  assert.match(pageSource, /function PositionRiskMap/);
  assert.match(pageSource, /buildPositionRiskMarkers/);
  assert.match(pageSource, /resolveRiskMarkerLayouts/);
  assert.match(pageSource, /detailLabel: formatTakeProfitClosePercent\(takeProfit\.closePercent\)/);
  assert.match(pageSource, /formatRiskMarkerLabel\(marker\)/);
  assert.match(pageSource, /formatRiskMapPrice\(marker\.price\)/);
  assert.match(pageSource, /function formatRiskMapPrice/);
  assert.match(pageSource, /function formatTakeProfitClosePercent/);
  assert.match(pageSource, /position-risk-guide/);
  assert.match(pageSource, /getRiskMarkerPlacement/);
  assert.match(pageSource, /getRiskMarkerLaneCount/);
  assert.match(pageSource, /getRiskMarkerAnchor/);
  assert.match(pageSource, /placeRiskLabelsInLanes/);
  assert.match(pageSource, /"--risk-left": `\$\{marker\.labelPercent\}%`/);
  assert.match(pageSource, /position-summary-grid/);
  assert.match(pageSource, /position-risk-map/);
  assert.match(pageSource, /No active position/);
  assert.match(pageSource, /NOT OPENED/);
  assert.match(stylesSource, /current-position-panel/);
  assert.match(stylesSource, /position-status-badge/);
  assert.match(stylesSource, /position-status-badge\.idle/);
  assert.match(stylesSource, /position-risk-marker/);
  assert.match(stylesSource, /position-risk-guide/);
  assert.match(stylesSource, /position-risk-dot\.mark::after/);
  assert.match(stylesSource, /mark-price-pulse/);
  assert.match(stylesSource, /prefers-reduced-motion: reduce/);
  assert.match(stylesSource, /width: 14px/);
  assert.match(stylesSource, /height: 14px/);
  assert.match(stylesSource, /min-width: 88px/);
  assert.match(stylesSource, /min-height: 218px/);
  assert.match(stylesSource, /edge-end/);
  assert.doesNotMatch(pageSource, /function CurrentTradeRow/);
  assert.doesNotMatch(pageSource, /current-trade-row/);
  assert.match(pageSource, /increaseDemoPosition/);
  assert.match(pageSource, /Add to Position/);
  assert.match(pageSource, /Add position size percent/);
  assert.match(pageSource, /commitDemoState/);
  assert.match(pageSource, /closeOpenPositionByPercent/);
  assert.match(pageSource, /Manual close size percent/);
  assert.match(pageSource, /openDemoPosition/);
  assert.match(pageSource, /placeDemoLimitOrder/);
  assert.match(pageSource, /cancelDemoLimitOrder/);
  assert.match(pageSource, /demoState\.pendingLimitOrder/);
  assert.doesNotMatch(pageSource, /setPendingLimitOrder/);
  assert.match(pageSource, /updateDemoStopLoss/);
  assert.match(pageSource, /updateDemoTakeProfits/);
  assert.match(pageSource, /updateDemoLeverage/);
  assert.match(pageSource, /Close at Market/);
  assert.match(pageSource, /primary-button danger-button candle-hover-button manual-close-button/);
  assert.match(stylesSource, /manual-close-button[\s\S]*box-shadow: none/);
  assert.match(pageSource, /Export CSV/);
  assert.match(pageSource, /ghost-button compact candle-hover-button/);
  assert.match(stylesSource, /demo-history-panel \.section-heading \{[\s\S]*justify-content: space-between/);
  const performancePanelIndex = pageSource.indexOf("<PerformanceStats stats={stats} />");
  const balancePanelIndex = pageSource.indexOf('className="section-panel demo-balance-panel no-hover-effect"');
  assert.ok(performancePanelIndex !== -1 && balancePanelIndex !== -1 && performancePanelIndex < balancePanelIndex);
  assert.match(stylesSource, /demo-summary-grid \{[\s\S]*grid-template-columns: minmax\(0, 1\.75fr\) minmax\(300px, 0\.62fr\)/);
  assert.match(stylesSource, /demo-summary-grid \{[\s\S]*align-items: stretch/);
  assert.match(stylesSource, /demo-balance-panel \{[\s\S]*align-content: start/);
  assert.match(pageSource, /Set a fresh practice balance before resetting/);
  assert.match(pageSource, /Your demo stats rebuild from the new starting balance/);
  assert.match(stylesSource, /demo-balance-copy/);
  assert.match(stylesSource, /demo-balance-note/);
  assert.match(pageSource, /Changing your starting demo balance will reset your current demo progress/);
  assert.match(pageSource, /Reset and Apply New Balance/);
});

test("BTC market data provider is isolated and uses public REST data", () => {
  assert.match(marketDataSource, /fetchDemoTradeCandles/);
  assert.match(marketDataSource, /fetchDemoTradeCandleResult/);
  assert.match(marketDataSource, /fetchDemoTradeMarketSnapshot/);
  assert.match(marketDataSource, /fetchDemoTradeTicker/);
  assert.match(marketDataSource, /subscribeDemoTradePriceStream/);
  assert.match(marketDataSource, /WebSocket/);
  assert.match(marketDataSource, /@trade/);
  assert.match(marketDataSource, /DemoTradeTimeframe = "1m" \| "5m" \| "15m" \| "1h" \| "4h" \| "6h" \| "12h" \| "1d" \| "1w" \| "1M"/);
  assert.match(marketDataSource, /api\.binance\.us\/api\/v3/);
  assert.match(marketDataSource, /api\.binance\.com\/api\/v3/);
  assert.match(marketDataSource, /api\.exchange\.coinbase\.com/);
  assert.match(marketDataSource, /api\.coinbase\.com\/v2\/prices\/BTC-USD\/spot/);
  assert.match(marketDataSource, /demoTradeMarketCacheKey/);
  assert.match(marketDataSource, /readCachedTicker/);
  assert.match(marketDataSource, /readCachedCandles/);
  assert.match(pageSource, /fetchDemoTradeMarketSnapshot/);
  assert.match(pageSource, /fetchDemoTradeCandleResult/);
  assert.match(pageSource, /Showing cached data while retrying/);
  assert.doesNotMatch(marketDataSource, /apiKey|secret|TradingView/);
});

test("registered demo state migration includes RLS and server-side validation", () => {
  assert.match(migrationSource, /create table if not exists public\.demo_trade_states/);
  assert.match(migrationSource, /enable row level security/);
  assert.match(migrationSource, /auth\.uid\(\) = user_id/);
  assert.match(migrationSource, /validate_demo_trade_state/);
  assert.match(migrationSource, /save_demo_trade_state/);
  assert.match(migrationSource, /BTCUSDT/);
  assert.match(grantMigrationSource, /grant select, insert, update on table public\.demo_trade_states to authenticated/);
  assert.match(grantMigrationSource, /grant execute on function public\.save_demo_trade_state\(jsonb\) to authenticated/);
  assert.match(grantMigrationSource, /notify pgrst, 'reload schema'/);
  assert.match(staleSaveMigrationSource, /demo_trade_state_updated_at/);
  assert.match(staleSaveMigrationSource, /public\.demo_trade_state_updated_at\(public\.demo_trade_states\.state\)/);
  assert.match(staleSaveMigrationSource, /<= incoming_updated_at/);
  assert.match(staleSaveMigrationSource, /notify pgrst, 'reload schema'/);
});
