import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const appSource = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
const layoutSource = await readFile(new URL("../src/components/Layout.tsx", import.meta.url), "utf8");
const pageSource = await readFile(new URL("../src/pages/DemoTrade.tsx", import.meta.url), "utf8");
const stylesSource = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
const persistenceSource = await readFile(new URL("../src/lib/demoTradePersistence.ts", import.meta.url), "utf8");
const reconciliationSource = await readFile(new URL("../src/lib/demoTradeReconciliation.ts", import.meta.url), "utf8");
const marketDataSource = await readFile(new URL("../src/lib/demoTradeMarketData.ts", import.meta.url), "utf8");
const riskMapSource = await readFile(new URL("../src/lib/demoTradeRiskMap.ts", import.meta.url), "utf8");
const reconcileFunctionSource = await readFile(new URL("../supabase/functions/demo-trade-reconcile/index.ts", import.meta.url), "utf8");
const migrationSource = await readFile(new URL("../supabase/migrations/202606160001_demo_trade.sql", import.meta.url), "utf8");
const grantMigrationSource = await readFile(new URL("../supabase/migrations/202606180001_demo_trade_persistence_grants.sql", import.meta.url), "utf8");
const staleSaveMigrationSource = await readFile(new URL("../supabase/migrations/202606180002_demo_trade_stale_save_guard.sql", import.meta.url), "utf8");
const serverReconciliationMigrationSource = await readFile(new URL("../supabase/migrations/202606180003_demo_trade_server_reconciliation.sql", import.meta.url), "utf8");
const serviceRoleGrantsMigrationSource = await readFile(new URL("../supabase/migrations/202606190002_demo_trade_service_role_grants.sql", import.meta.url), "utf8");
const terminalCloseGuardMigrationSource = await readFile(new URL("../supabase/migrations/202606190004_demo_trade_terminal_close_guard.sql", import.meta.url), "utf8");

test("Demo Trade page renders as a public route", () => {
  assert.match(appSource, /import \{ DemoTrade \} from "\.\/pages\/DemoTrade"/);
  assert.match(appSource, /path="demo-trade" element=\{<DemoTrade \/>\}/);
  assert.doesNotMatch(appSource, /path="demo-trade"[\s\S]{0,120}ProtectedRoute/);
});

test("header contains Demo Trade link for all users", () => {
  assert.match(layoutSource, /to: "\/demo-trade", label: "Demo Trade"/);
  assert.match(layoutSource, /ChartCandlestick/);
});

test("Demo Trade page includes guest and authenticated persistence paths", () => {
  assert.match(pageSource, /loadGuestDemoTradeState/);
  assert.match(pageSource, /saveGuestDemoTradeState/);
  assert.match(pageSource, /loadRegisteredDemoTradeState/);
  assert.match(pageSource, /saveRegisteredDemoTradeState/);
  assert.match(persistenceSource, /window\.sessionStorage/);
  assert.match(persistenceSource, /window\.localStorage/);
  assert.match(persistenceSource, /registeredStateKey/);
  assert.match(persistenceSource, /chooseLatestState/);
  assert.match(persistenceSource, /demo_trade_states/);
  assert.match(persistenceSource, /save_demo_trade_state/);
  assert.match(persistenceSource, /demo-trade-reconcile/);
  assert.match(persistenceSource, /RegisteredDemoTradeLoadResult/);
  assert.match(persistenceSource, /isAccountSyncAvailable/);
  assert.match(persistenceSource, /mergeBracketOrdersForSameOpenPosition/);
  assert.match(persistenceSource, /normalizeStoredOpenPosition/);
  assert.match(persistenceSource, /REGISTERED_SAVE_ERROR_MESSAGE/);
  assert.match(persistenceSource, /onConflict: "user_id"/);
  assert.match(persistenceSource, /throw new Error\(REGISTERED_SAVE_ERROR_MESSAGE\)/);
  assert.match(pageSource, /DEMO_TRADE_LOAD_ERROR_MESSAGE/);
  assert.match(pageSource, /persistenceError/);
  assert.match(pageSource, /setIsHydrated\(false\)/);
  assert.match(pageSource, /setIsHydrated\(isAccountSyncAvailable\)/);
  assert.match(pageSource, /Demo trade progress could not be saved to your account/);
});

test("registered Demo Trade has backend reconciliation primitives", () => {
  assert.match(reconciliationSource, /reconcileDemoTradeStateWithCandles/);
  assert.match(reconciliationSource, /eventType: "limit_fill"/);
  assert.match(reconciliationSource, /liquidation first, then stop loss, then take profits/);
  assert.match(reconcileFunctionSource, /fetchHistoricalCandles/);
  assert.match(reconcileFunctionSource, /save_reconciled_demo_trade_state/);
  assert.match(reconcileFunctionSource, /scope === "all"/);
  assert.match(reconcileFunctionSource, /hasReconcilableDemoState/);
  assert.match(reconcileFunctionSource, /row\.state\.openPosition \|\| row\.state\.pendingLimitOrder/);
  assert.match(reconcileFunctionSource, /position\?\.lastCheckedAt \?\? position\?\.openedAt \?\? pendingOrder\?\.updatedAt \?\? pendingOrder\?\.createdAt/);
  assert.doesNotMatch(reconcileFunctionSource, /\.not\("open_position", "is", null\)/);
  assert.match(serverReconciliationMigrationSource, /demo_trade_execution_events/);
  assert.match(serverReconciliationMigrationSource, /'limit_fill'/);
  assert.match(serverReconciliationMigrationSource, /unique \(user_id, trade_id, event_key\)/);
  assert.match(serverReconciliationMigrationSource, /for update/);
  assert.match(serverReconciliationMigrationSource, /cron\.schedule/);
  assert.match(serverReconciliationMigrationSource, /demo-trade-reconcile-every-5-minutes/);
  assert.match(serviceRoleGrantsMigrationSource, /grant select, insert, update on table public\.demo_trade_states to service_role/);
  assert.match(serviceRoleGrantsMigrationSource, /grant select, insert on table public\.demo_trade_execution_events to service_role/);
  assert.match(terminalCloseGuardMigrationSource, /demo_trade_state_has_closed_trade/);
  assert.match(terminalCloseGuardMigrationSource, /jsonb_array_elements\(coalesce\(next_state->'tradeHistory'/);
  assert.match(terminalCloseGuardMigrationSource, /or public\.demo_trade_state_has_closed_trade/);
});

test("Demo Trade does not account-save ordinary market ticks over bracket edits", () => {
  assert.match(pageSource, /pendingMarketStateToPersistRef/);
  assert.match(pageSource, /shouldPersistMarketState/);
  assert.match(pageSource, /isCachedMarketSource/);
  assert.match(pageSource, /if \(!isCachedMarketSource\(ticker\.source\)\) \{[\s\S]*applyMarketPriceToDemoState\(ticker\.price, ticker\.timestamp\)/);
  assert.match(pageSource, /if \(!isCachedMarketSource\(snapshot\.ticker\.source\)\) \{[\s\S]*applyMarketPriceToDemoState\(snapshot\.ticker\.price, snapshot\.ticker\.timestamp\)/);
  assert.match(pageSource, /applyMarketPriceToDemoState/);
  assert.match(pageSource, /persistDemoState\(pendingMarketState\)/);
  assert.match(pageSource, /const commitDemoState = useCallback\(\(nextState: DemoTradeState\) => \{\s*pendingMarketStateToPersistRef\.current = null;/);
  assert.match(pageSource, /pendingMarketStateToPersistRef\.current = null;\s*if \(pendingMarketState !== demoState\) return;\s*persistDemoState\(pendingMarketState\)/);
  assert.doesNotMatch(pageSource, /window\.setTimeout\(\(\) => \{\s*const save = user/);
});

test("Demo Trade page includes custom chart and no TradingView widget", () => {
  assert.match(pageSource, /function DemoTradeChart/);
  assert.match(pageSource, /chartClassName/);
  assert.match(pageSource, /buildOverlayLines/);
  assert.doesNotMatch(pageSource, /TradingViewChart|tradingview-widget|s3\.tradingview/);
});

test("Demo Trade chart has timeframe tabs, right price scale, and compact controls", () => {
  assert.match(pageSource, /demoTradeTimeframes\.map/);
  assert.doesNotMatch(marketDataSource, /\{ value: "1m", label: "1m" \}/);
  assert.match(pageSource, /chart-axis-panel/);
  assert.match(pageSource, /chart-price-label/);
  assert.match(pageSource, /onContextMenu=\{\(event\) => event\.preventDefault\(\)\}/);
  assert.match(pageSource, /onPointerDown=\{startRightDrag\}/);
  assert.match(pageSource, /onLostPointerCapture=\{stopRightDrag\}/);
  assert.match(pageSource, /onWheel=\{handleChartWheel\}/);
  assert.match(pageSource, /onDoubleClick=\{resetPriceView\}/);
  assert.match(pageSource, /dragStartRef\.current \|\| priceScaleStartRef\.current\) return/);
  assert.match(pageSource, /setPointerCapture/);
  assert.match(pageSource, /event\.pointerType === "mouse" && event\.buttons === 0/);
  assert.match(pageSource, /const rawDeltaX = event\.clientX - dragStartRef\.current\.x/);
  assert.match(pageSource, /dragPreviewX/);
  assert.match(pageSource, /className="chart-candle-layer" transform=\{dragPreviewX \? `translate\(\$\{dragPreviewX\} 0\)` : undefined\}/);
  assert.match(pageSource, /futurePaddingCandles/);
  assert.match(pageSource, /pricePan/);
  assert.match(pageSource, /visiblePriceRange/);
  assert.match(pageSource, /DEMO_CHART_DRAG_ACTIVATION_PX = 4/);
  assert.match(pageSource, /DEMO_CHART_AXIS_SCALE_VERTICAL_BIAS = 1\.15/);
  assert.match(pageSource, /DEMO_CHART_BOUNDARY_DRAG_RESISTANCE = 0\.22/);
  assert.match(pageSource, /absDeltaX > absDeltaY \* DEMO_CHART_AXIS_SCALE_VERTICAL_BIAS/);
  assert.match(pageSource, /setDragPreviewX\(didHitBoundary \? rawPreviewX \* DEMO_CHART_BOUNDARY_DRAG_RESISTANCE : rawPreviewX\)/);
  assert.match(pageSource, /setPricePan\(dragStartRef\.current\.pricePan \+ deltaY \* pricePerPixel\)/);
  assert.match(pageSource, /DEMO_TRADE_CHART_CANDLE_LIMIT/);
  assert.match(pageSource, /fetchDemoTradeMarketSnapshot\(activeSymbol\.symbol, timeframe, DEMO_TRADE_CHART_CANDLE_LIMIT\)/);
  assert.match(pageSource, /fetchDemoTradeCandleResult\(activeSymbol\.symbol, timeframe, DEMO_TRADE_CHART_CANDLE_LIMIT\)/);
  assert.match(pageSource, /nextCandles\.slice\(-DEMO_TRADE_CHART_CANDLE_LIMIT\)/);
  assert.match(pageSource, /MIN_DEMO_CHART_PRICE_SCALE = 0\.16/);
  assert.match(pageSource, /MAX_DEMO_CHART_PRICE_SCALE = 8/);
  assert.match(pageSource, /DEMO_CHART_PRICE_SCALE_DRAG_SENSITIVITY = 150/);
  assert.match(pageSource, /DEMO_CHART_PRICE_SCALE_WHEEL_SENSITIVITY = 420/);
  assert.match(pageSource, /activeScaleStart\.scale \* Math\.exp\(activeDeltaY \/ DEMO_CHART_PRICE_SCALE_DRAG_SENSITIVITY\)/);
  assert.match(pageSource, /event\.deltaY \/ DEMO_CHART_PRICE_SCALE_WHEEL_SENSITIVITY/);
  assert.match(pageSource, /setPriceScale\(\(scale\) => clamp\(scale \* scaleFactor, MIN_DEMO_CHART_PRICE_SCALE, MAX_DEMO_CHART_PRICE_SCALE\)\)/);
  assert.match(pageSource, /wheelPanRemainderRef/);
  assert.match(pageSource, /const horizontalDelta = Math\.abs\(event\.deltaX\) >= Math\.abs\(event\.deltaY\)/);
  assert.match(pageSource, /wheelPanRemainderRef\.current \+= horizontalDelta \/ Math\.max\(6, candleGap\)/);
  assert.match(pageSource, /setOffset\(\(value\) => clamp\(value - deltaCandles, -futurePaddingCandles, maxOffset\)\)/);
  assert.doesNotMatch(pageSource, /0\.45, 4/);
  assert.match(pageSource, /priceScaleStartRef/);
  assert.match(pageSource, /crosshair/);
  assert.match(pageSource, /updateCrosshair/);
  assert.match(pageSource, /getSvgPointer/);
  assert.match(pageSource, /chart-crosshair-price/);
  assert.match(pageSource, /line\.tone !== "liquidation"/);
  assert.match(pageSource, /label: "Entry", price: position\.entryPrice/);
  assert.match(pageSource, /pendingLimitOrder=\{demoState\.pendingLimitOrder\}/);
  assert.match(pageSource, /buildOverlayLines\(position, pendingLimitOrder, currentPrice\)/);
  assert.match(pageSource, /label: "Limit", price: pendingLimitOrder\.limitPrice, tone: "pending"/);
  assert.match(pageSource, /subscribeDemoTradePriceStream/);
  assert.match(pageSource, /applyLiveTicker/);
  assert.match(pageSource, /getCandleBucketStart/);
  assert.match(pageSource, /startRightDrag/);
  assert.match(pageSource, /ZoomIn/);
  assert.match(pageSource, /ZoomOut/);
  assert.match(pageSource, /isBullishCandle/);
  assert.doesNotMatch(pageSource, /latestCandleTone/);
  assert.match(pageSource, /resolveOverlayMarkerLayouts/);
  assert.match(pageSource, /resolveOverlayMarkerCluster/);
  assert.match(pageSource, /a\.markerY - b\.markerY \|\| b\.line\.price - a\.line\.price \|\| a\.index - b\.index/);
  assert.match(pageSource, /line\.tone === "entry" && position \? `side-\$\{position\.side\}` : ""/);
  assert.match(pageSource, /chart-marker-connector/);
  assert.match(pageSource, /isOverlayPriceMarker/);
  assert.match(pageSource, /chart-price-marker-label/);
  assert.match(stylesSource, /chart-marker-connector/);
  assert.match(stylesSource, /trade-overlay-line\.mark line:not\(\.chart-marker-connector\)/);
  assert.match(stylesSource, /stroke-dasharray: 1 7/);
  assert.match(stylesSource, /trade-overlay-line\.mark \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.entry \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.entry line \{[^}]*stroke: rgba\(229, 228, 226, 0\.68\)/);
  assert.match(stylesSource, /trade-overlay-line\.entry\.side-long \.chart-price-marker \{[^}]*fill: rgba\(69, 174, 116, 0\.92\)/);
  assert.match(stylesSource, /trade-overlay-line\.entry\.side-short \.chart-price-marker \{[^}]*fill: rgba\(210, 71, 77, 0\.92\)/);
  assert.doesNotMatch(stylesSource, /trade-overlay-line\.entry line \{[^}]*rgba\(184, 214, 222/);
  assert.match(stylesSource, /trade-overlay-line\.pending line/);
  assert.match(stylesSource, /trade-overlay-line\.pending \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.target \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.danger \.chart-price-marker/);
  assert.match(stylesSource, /trade-overlay-line\.liquidation \.chart-price-marker/);
  assert.match(stylesSource, /demo-timeframe-tabs button\.active \{[^}]*border-color: rgba\(229, 228, 226, 0\.34\)/);
  assert.doesNotMatch(stylesSource, /demo-timeframe-tabs button\.active \{[^}]*rgba\(126, 224, 167/);
  assert.match(stylesSource, /aspect-ratio: 1/);
  assert.match(pageSource, /DEMO_TRADE_LIVE_REFRESH_MS = 1000/);
  assert.match(pageSource, /DEMO_TRADE_CANDLE_SYNC_MS = 10000/);
  assert.match(pageSource, /applyLivePriceToCandles/);
  assert.match(pageSource, /buildCandleShape/);
  assert.match(pageSource, /snapCandleBodyWidth\(clamp\(candleGap \* 0\.76, 7, 20\)\)/);
  assert.match(pageSource, /const candleX = snapSvgCoordinate/);
  assert.match(pageSource, /function snapSvgCoordinate/);
  assert.match(stylesSource, /\.candle-body \{[\s\S]*stroke-width: 0[\s\S]*shape-rendering: crispEdges/);
  assert.match(pageSource, /minWickHeight/);
  assert.doesNotMatch(pageSource, /clampPricePan|minPricePan|maxPricePan|clampedPricePan/);
  assert.doesNotMatch(pageSource, /chartTop|chartBottom/);
  assert.match(marketDataSource, /"6h"/);
  assert.match(marketDataSource, /"12h"/);
  assert.match(marketDataSource, /"1M"/);
  assert.doesNotMatch(pageSource, /Zoom In|Zoom Out|Pan Left|Pan Right/);
  assert.doesNotMatch(pageSource, /ArrowLeft|ArrowRight/);
});

test("Demo Trade position risk map centers guide lines on smaller price dots", () => {
  assert.match(pageSource, /function PositionRiskMap/);
  assert.match(pageSource, /buildPositionRiskMarkers/);
  assert.match(pageSource, /resolveRiskMarkerLayouts/);
  assert.match(pageSource, /position\.leverage > 1 && isFiniteNumber\(position\.liquidationPrice\) && position\.liquidationPrice > 0/);
  assert.match(pageSource, /if \(!Number\.isFinite\(value\) \|\| value <= 0\) return "--"/);
  assert.match(riskMapSource, /marker\.price > 0/);
  assert.match(pageSource, /"--risk-left": `\$\{marker\.percent\}%`/);
  assert.match(pageSource, /position-risk-guide-link/);
  assert.match(pageSource, /"--risk-link-left": `\$\{Math\.min\(marker\.percent, marker\.labelPercent\)\}%`/);
  assert.match(pageSource, /"--risk-link-width": `\$\{Math\.abs\(marker\.labelPercent - marker\.percent\)\}%`/);
  assert.match(stylesSource, /--risk-axis-y: 132px/);
  assert.match(stylesSource, /--risk-dot-size: 8\.4px/);
  assert.match(stylesSource, /--risk-dot-radius: 4\.2px/);
  assert.match(stylesSource, /top: calc\(var\(--risk-axis-y\) - var\(--risk-dot-radius\)\)/);
  assert.match(stylesSource, /height: max\(10px, calc\(var\(--risk-axis-y\) - 36px - \(var\(--risk-lane, 0\) \* 40px\)\)\)/);
  assert.match(stylesSource, /position-risk-guide-link\.below \{[\s\S]*top: calc\(var\(--risk-axis-y\) \+ 34px\)/);
  assert.match(stylesSource, /inset: -3\.6px/);
});

test("Demo Trade compressed risk map uses ellipsis break marker", () => {
  assert.match(stylesSource, /position-risk-axis::before \{[^}]*content: "\.\.\."/);
  assert.match(stylesSource, /position-risk-axis::before \{[^}]*color: rgba\(255, 107, 107, 0\.72\)/);
  assert.match(stylesSource, /position-risk-track\.compressed-left \.position-risk-axis::before \{[^}]*display: block/);
  assert.doesNotMatch(stylesSource, /position-risk-axis::before \{[^}]*border-radius/);
  assert.doesNotMatch(stylesSource, /position-risk-axis::before \{[^}]*background:/);
  assert.doesNotMatch(stylesSource, /position-risk-axis::before \{[^}]*skewX/);
});

test("Demo Trade position risk map shows entry-to-mark progress by PnL direction", () => {
  assert.match(pageSource, /interface PositionRiskProgressSegment/);
  assert.match(pageSource, /buildRiskMapProgressSegment\(markers, position, markPrice\)/);
  assert.match(pageSource, /className=\{`position-risk-progress \$\{riskProgress\.tone\}`\}/);
  assert.match(pageSource, /"--risk-progress-left": `\$\{riskProgress\.startPercent\}%`/);
  assert.match(pageSource, /"--risk-progress-width": `\$\{riskProgress\.widthPercent\}%`/);
  assert.match(pageSource, /position\.side === "long" \? activeMarkPrice >= position\.entryPrice : activeMarkPrice <= position\.entryPrice/);
  assert.match(pageSource, /position-risk-track \$\{riskScale\.mode\} side-\$\{position\.side\}/);
  assert.match(stylesSource, /position-risk-progress\.positive/);
  assert.match(stylesSource, /position-risk-progress\.negative/);
  assert.match(stylesSource, /position-risk-track\.side-long \.position-risk-marker\.entry/);
  assert.match(stylesSource, /position-risk-track\.side-short \.position-risk-marker\.entry/);
  assert.match(stylesSource, /position-risk-track\.side-long \.position-risk-guide\.entry,[\s\S]*position-risk-track\.side-long \.position-risk-guide-link\.entry \{[\s\S]*background: rgba\(126, 224, 167, 0\.5\)/);
  assert.match(stylesSource, /position-risk-track\.side-short \.position-risk-guide\.entry,[\s\S]*position-risk-track\.side-short \.position-risk-guide-link\.entry \{[\s\S]*background: rgba\(255, 107, 107, 0\.5\)/);
  assert.match(stylesSource, /position-risk-track\.side-long \.position-risk-dot\.entry \{[\s\S]*background: var\(--success\)/);
  assert.match(stylesSource, /position-risk-track\.side-short \.position-risk-dot\.entry \{[\s\S]*background: var\(--danger\)/);
  assert.match(stylesSource, /position-risk-track\.side-long \.position-risk-marker\.entry \{[^}]*background: rgba\(126, 224, 167, 0\.13\)/);
  assert.match(stylesSource, /position-risk-track\.side-short \.position-risk-marker\.entry \{[^}]*background: rgba\(255, 107, 107, 0\.13\)/);
  assert.doesNotMatch(stylesSource, /position-risk-track\.side-long \.position-risk-marker\.entry \{[^}]*linear-gradient/);
  assert.doesNotMatch(stylesSource, /position-risk-track\.side-short \.position-risk-marker\.entry \{[^}]*linear-gradient/);
  assert.match(stylesSource, /animation: risk-progress-pulse 2\.4s ease-in-out infinite/);
  assert.match(stylesSource, /@keyframes risk-progress-pulse/);
  assert.match(stylesSource, /\.position-risk-dot\.mark::after,\s*\.position-risk-progress/);
});

test("Demo Trade reset balance button uses standard compact hover", () => {
  const resetButtonIndex = pageSource.indexOf('onClick={requestBalanceReset}');
  assert.ok(resetButtonIndex !== -1);
  const balancePanelIndex = pageSource.indexOf('className="section-panel demo-balance-panel no-hover-effect"');
  assert.ok(balancePanelIndex !== -1);
  const balancePanelSource = pageSource.slice(balancePanelIndex, pageSource.indexOf("</article>", balancePanelIndex));
  assert.ok(balancePanelSource.indexOf("Clean reset") < balancePanelSource.indexOf("Starting Balance"));
  assert.ok(balancePanelSource.indexOf("Starting Balance") < balancePanelSource.indexOf("Reset and Apply New Balance"));
  const resetButtonSource = pageSource.slice(Math.max(0, resetButtonIndex - 140), resetButtonIndex + 180);
  assert.match(resetButtonSource, /className="ghost-button compact"/);
  assert.doesNotMatch(resetButtonSource, /candle-hover-button/);
  assert.match(resetButtonSource, /Reset and Apply New Balance/);
  assert.match(stylesSource, /demo-balance-panel \{[\s\S]*grid-template-rows: auto auto auto minmax\(0, 1fr\)/);
  assert.match(stylesSource, /demo-balance-panel > \.ghost-button \{[\s\S]*align-self: end/);
  assert.match(stylesSource, /demo-balance-note \{[\s\S]*border: 1px solid rgba\(229, 228, 226, 0\.08\)/);
  assert.match(stylesSource, /demo-balance-note \{[\s\S]*background: rgba\(229, 228, 226, 0\.035\)/);
  assert.match(stylesSource, /demo-balance-note strong \{[\s\S]*color: rgba\(184, 196, 207, 0\.72\)/);
  assert.doesNotMatch(stylesSource, /demo-balance-note strong \{[^}]*color: var\(--success\)/);
});

test("Demo Trade page includes trade ticket, management, CSV export, and reset modal", () => {
  assert.match(pageSource, /function TradeEntryForm/);
  assert.match(pageSource, /futures-ticket/);
  assert.match(stylesSource, /align-items: stretch/);
  assert.match(stylesSource, /demo-ticket-panel[\s\S]*align-self: stretch/);
  assert.match(pageSource, /type DemoQuantityUnit = "usdt" \| "btc" \| "cont"/);
  assert.match(pageSource, /type DemoStopLossInputMode = "price" \| "percent"/);
  assert.match(pageSource, /type DemoTakeProfitInputMode = "price" \| "percent"/);
  assert.match(pageSource, /function QuantityUnitSelector/);
  assert.match(pageSource, /ORDER BY QUANTITY/);
  assert.match(pageSource, /aria-label="Set quantity unit"/);
  assert.match(pageSource, /onQuantityUnitChange=\{applyQuantityUnit\}/);
  assert.match(pageSource, /quantityUnitLabels/);
  assert.match(pageSource, /DEMO_CONTRACT_BTC_SIZE = 0\.0001/);
  assert.match(pageSource, /quantityInputToNotional/);
  assert.match(pageSource, /notionalToQuantityInput/);
  assert.match(pageSource, /convertQuantityInput/);
  assert.match(pageSource, /quantityUnit=\{quantityUnit\}/);
  assert.match(pageSource, /placeDemoLimitOrder/);
  assert.match(pageSource, /quantityInputToNotional\(amountValue, quantityUnit, nextLimitPrice\)/);
  assert.match(pageSource, /Quantity \(\{unitLabel\}\)/);
  assert.match(stylesSource, /unit-popover/);
  assert.match(stylesSource, /unit-option-grid/);
  assert.match(stylesSource, /futures-quantity-label/);
  assert.doesNotMatch(pageSource, /Futures Unit Settings|showQuantityUnitModal|draftQuantityUnit/);
  assert.doesNotMatch(stylesSource, /futures-unit-modal/);
  assert.match(pageSource, /BTCUSDT Perpetual/);
  assert.match(pageSource, /Limit orders are available for registered users only/);
  assert.match(pageSource, /Limit Price/);
  assert.match(pageSource, /marginMode/);
  assert.match(pageSource, /Margin mode/);
  assert.match(pageSource, /function MarginModeSelector/);
  assert.match(pageSource, /MARGIN MODE/);
  assert.match(pageSource, /aria-label="Set margin mode"/);
  assert.match(pageSource, /marginModeLabels/);
  assert.match(stylesSource, /margin-mode-popover/);
  assert.match(stylesSource, /margin-mode-option-grid/);
  assert.match(pageSource, /function LeverageSelector/);
  assert.match(pageSource, /SET LEVERAGE/);
  assert.match(pageSource, /aria-label="Set leverage"/);
  assert.match(pageSource, /aria-label="Decrease leverage"/);
  assert.match(pageSource, /aria-label="Increase leverage"/);
  assert.match(pageSource, /aria-label="Leverage slider"/);
  assert.match(pageSource, /onApply\(String\(nextLeverage\)\)/);
  assert.match(stylesSource, /leverage-popover/);
  assert.match(stylesSource, /leverage-stepper/);
  assert.doesNotMatch(pageSource, /select[\s\S]{0,160}value=\{marginMode\}/);
  assert.doesNotMatch(pageSource, /select className="futures-mode-chip" value=\{leverage\}/);
  assert.match(pageSource, /Cross/);
  assert.match(pageSource, /liquidationCollateral/);
  assert.match(pageSource, /isBracketEnabled/);
  assert.match(pageSource, /stopLossInputMode/);
  assert.match(pageSource, /function StopLossModeSelector/);
  assert.match(pageSource, /STOP LOSS BY/);
  assert.match(pageSource, /aria-label="Set stop loss input mode"/);
  assert.match(pageSource, /resolveSubmittedStopLoss\(stopLoss, stopLossInputMode, side, referencePrice\)/);
  assert.match(pageSource, /side === "long"[\s\S]*referencePrice \* \(1 - stopDistance\)[\s\S]*referencePrice \* \(1 \+ stopDistance\)/);
  assert.match(stylesSource, /stop-loss-mode-popover/);
  assert.match(stylesSource, /stop-loss-mode-option-grid/);
  assert.match(pageSource, /function TakeProfitModeSelector/);
  assert.match(pageSource, /TAKE PROFIT BY/);
  assert.match(pageSource, /aria-label="Set take profit input mode"/);
  assert.match(pageSource, /resolveSubmittedTakeProfitPrice\(takeProfit\.price, takeProfitInputMode, side, referencePrice\)/);
  assert.match(pageSource, /side === "long"[\s\S]*referencePrice \* \(1 \+ targetDistance\)[\s\S]*referencePrice \* \(1 - targetDistance\)/);
  assert.match(stylesSource, /take-profit-mode-popover/);
  assert.match(stylesSource, /take-profit-mode-option-grid/);
  assert.match(stylesSource, /right: var\(--tp-mode-popover-inset\)/);
  assert.match(stylesSource, /left: var\(--tp-mode-popover-inset\)/);
  assert.match(pageSource, /stopLoss: 0/);
  assert.match(pageSource, /floorTo/);
  assert.match(pageSource, /Position size percent/);
  assert.match(pageSource, /percentSliderStyle/);
  assert.match(stylesSource, /--slider-thumb-center/);
  assert.match(stylesSource, /--slider-quarter-offset/);
  assert.match(stylesSource, /futures-percent-marks span:nth-child\(4\)/);
  assert.match(pageSource, /Long Liquidation Price/);
  assert.match(pageSource, /Open Long/);
  assert.match(pageSource, /Open Short/);
  assert.match(pageSource, /ORDER BY QUANTITY/);
  assert.match(stylesSource, /unit-option-grid button\.active \{[^}]*color: var\(--platinum\)/);
  assert.doesNotMatch(stylesSource, /unit-option-grid button\.active \{[^}]*color: var\(--success\)/);
  assert.match(pageSource, /primary-button futures-submit long candle-hover-button/);
  assert.match(pageSource, /primary-button futures-submit short candle-hover-button/);
  assert.match(pageSource, /data-hover-chart-tone="success"/);
  assert.match(pageSource, /data-hover-chart-tone="danger"/);
  assert.match(stylesSource, /candle-hover-button:hover:not\(:disabled\)/);
  assert.match(stylesSource, /--button-candlestick-chart-overlay/);
  assert.match(stylesSource, /viewBox='0 0 280 58'/);
  assert.match(stylesSource, /hover-chart-size, calc\(100% - 8px\) calc\(100% - 6px\)/);
  assert.match(stylesSource, /var\(--button-candlestick-chart-overlay, var\(--btc-chart-overlay\)\)/);
  assert.match(stylesSource, /primary-button:not\(\.compact\):not\(\.candle-hover-button\):hover/);
  assert.doesNotMatch(pageSource, /Chase Limit/);
  assert.doesNotMatch(pageSource, /Position Size/);
  assert.doesNotMatch(pageSource, />S<\/span>/);
  assert.doesNotMatch(pageSource, /futures-direction-toggle/);
  assert.doesNotMatch(pageSource, /Refresh BTC/);
  assert.doesNotMatch(pageSource, /Data \/ Save/);
  assert.doesNotMatch(pageSource, /Saving\.\.\.|Ready/);
  assert.doesNotMatch(pageSource, /Trigger Price|pendingTriggerOrder|isTriggerPriceReached/);
  assert.match(pageSource, /function PositionManager/);
  assert.match(pageSource, /const savePositionChanges = \(\) => \{/);
  assert.match(pageSource, /positionStopLossInputMode/);
  assert.match(pageSource, /resolveSubmittedStopLoss\(positionStopLoss, positionStopLossInputMode, position\.side, position\.entryPrice\)/);
  assert.match(pageSource, /<StopLossModeSelector mode=\{stopLossInputMode\} onApply=\{onStopLossInputModeChange\} \/>/);
  assert.match(pageSource, /placeholder=\{stopLossInputMode === "percent" \? "SL distance %" : "Stop price"\}/);
  assert.match(pageSource, /onSaveChanges=\{savePositionChanges\}/);
  assert.match(pageSource, /Save Changes/);
  assert.match(pageSource, /haveTakeProfitDraftsChanged/);
  assert.match(pageSource, /<LeverageSelector leverage=\{leverage\} onApply=\{onLeverageChange\} \/>/);
  assert.match(stylesSource, /position-settings-grid/);
  assert.doesNotMatch(pageSource, /Update SL/);
  assert.doesNotMatch(pageSource, /Save TP Changes/);
  assert.doesNotMatch(pageSource, /select value=\{leverage\}/);
  assert.match(pageSource, /function CurrentPositionPanel/);
  assert.match(pageSource, /pendingLimitOrder=\{demoState\.pendingLimitOrder\}/);
  assert.match(pageSource, /onCancelPendingLimitOrder=\{cancelLimitOrder\}/);
  assert.match(pageSource, /PENDING LIMIT/);
  assert.match(pageSource, /Pending limit order/);
  assert.match(pageSource, /Not opened yet/);
  assert.match(pageSource, /before it becomes an active position/);
  assert.match(pageSource, /Pending bracket orders/);
  assert.match(pageSource, /formatPendingBracketPrice\(pendingLimitOrder\.stopLoss\)/);
  assert.match(pageSource, /formatPendingTakeProfit\(takeProfit\)/);
  assert.match(pageSource, /Take Profits" value="Blank"/);
  assert.match(pageSource, /function formatPendingTakeProfit/);
  assert.match(pageSource, /Cancel pending order/);
  assert.match(pageSource, /function PositionRiskMap/);
  assert.match(pageSource, /buildPositionRiskMarkers/);
  assert.match(pageSource, /resolveRiskMarkerLayouts/);
  assert.match(pageSource, /resolvePositionRiskScale\(rawMarkers\)/);
  assert.match(riskMapSource, /resolveCompressedLiquidationScale/);
  assert.match(riskMapSource, /compressed-left/);
  assert.match(riskMapSource, /isInvertedRiskScale/);
  assert.match(riskMapSource, /FAR_LIQUIDATION_ACTIVE_BAND_LEFT/);
  assert.match(pageSource, /detailLabel: formatTakeProfitClosePercent\(takeProfit\.closePercent\)/);
  assert.match(pageSource, /function rebalanceTakeProfitPercents/);
  assert.match(pageSource, /function splitTakeProfitPercents/);
  assert.match(pageSource, /const nextRows = \[\.\.\.takeProfits, \{ id: `tp-\$\{Date\.now\(\)\}`/);
  assert.match(pageSource, /const \[takeProfitInputMode, setTakeProfitInputMode\] = useState<DemoTakeProfitInputMode>\("price"\)/);
  assert.match(pageSource, /const \[positionTakeProfitInputMode, setPositionTakeProfitInputMode\] = useState<DemoTakeProfitInputMode>\("price"\)/);
  assert.match(pageSource, /inputMode=\{takeProfitInputMode\}/);
  assert.match(pageSource, /onInputModeChange=\{onTakeProfitInputModeChange\}/);
  assert.doesNotMatch(pageSource, /priceInputMode/);
  assert.match(pageSource, /onChange\(rebalanceTakeProfitPercents\(nextRows\)\)/);
  assert.match(pageSource, /const updateClosePercent = \(id: string, value: string\) => \{/);
  assert.match(pageSource, /onChange\(rebalanceTakeProfitPercents\(takeProfits, id, value\)\)/);
  assert.match(pageSource, /onChange=\{\(event\) => updateClosePercent\(takeProfit\.id, event\.target\.value\)\}/);
  assert.match(pageSource, /step="0\.1"/);
  assert.ok(pageSource.indexOf("{takeProfits.map((takeProfit, index) => (") < pageSource.indexOf('className="tp-builder-heading"'));
  assert.match(stylesSource, /\.tp-builder \{[^}]*--tp-action-size: 38px/);
  assert.match(stylesSource, /\.tp-builder-heading \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(90px, 0\.5fr\) var\(--tp-action-size\)/);
  assert.match(stylesSource, /\.tp-builder \.icon-button \{[^}]*width: var\(--tp-action-size\)[^}]*height: var\(--tp-action-size\)/);
  assert.match(stylesSource, /\.futures-ticket \.tp-builder-heading \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(72px, 0\.45fr\) var\(--tp-action-size\)/);
  assert.match(pageSource, /formatRiskMarkerLabel\(marker\)/);
  assert.match(pageSource, /formatRiskMapPrice\(marker\.price\)/);
  assert.match(pageSource, /function formatRiskMapPrice/);
  assert.match(pageSource, /function formatTakeProfitClosePercent/);
  assert.match(pageSource, /position-risk-guide/);
  assert.match(riskMapSource, /getRiskMarkerPlacement/);
  assert.match(riskMapSource, /getRiskMarkerLaneCount/);
  assert.match(riskMapSource, /function getRiskMarkerLaneOrder/);
  assert.match(riskMapSource, /marker\.tone === "take-profit" \? lanes\.reverse\(\) : lanes/);
  assert.match(riskMapSource, /getRiskMarkerAnchor/);
  assert.match(riskMapSource, /placeRiskLabelsInLanes/);
  assert.match(pageSource, /"--risk-left": `\$\{marker\.labelPercent\}%`/);
  assert.match(pageSource, /position-summary-grid/);
  assert.match(pageSource, /position-risk-map/);
  assert.match(pageSource, /No active position/);
  assert.match(pageSource, /NOT OPENED/);
  assert.match(stylesSource, /current-position-panel/);
  assert.match(stylesSource, /position-status-badge/);
  assert.match(stylesSource, /position-status-badge\.idle/);
  assert.match(stylesSource, /position-status-badge\.pending/);
  assert.match(stylesSource, /position-pending-state/);
  assert.match(stylesSource, /pending-limit-grid/);
  assert.match(stylesSource, /pending-bracket-grid/);
  assert.doesNotMatch(pageSource, /futures-pending-limit/);
  assert.match(stylesSource, /position-risk-marker/);
  assert.match(stylesSource, /position-risk-guide/);
  assert.match(stylesSource, /position-risk-track\.compressed-left/);
  assert.doesNotMatch(stylesSource, /position-risk-track\.compressed-right/);
  assert.match(stylesSource, /position-risk-dot\.mark::after/);
  assert.match(stylesSource, /mark-price-pulse/);
  assert.match(stylesSource, /prefers-reduced-motion: reduce/);
  assert.match(stylesSource, /width: 14px/);
  assert.match(stylesSource, /height: 14px/);
  assert.match(stylesSource, /min-width: 88px/);
  assert.match(stylesSource, /min-height: 218px/);
  assert.match(stylesSource, /edge-end/);
  assert.doesNotMatch(pageSource, /function CurrentTradeRow/);
  assert.doesNotMatch(pageSource, /current-trade-row/);
  assert.match(pageSource, /increaseDemoPosition/);
  assert.match(pageSource, /Add to Position/);
  assert.match(pageSource, /Add position size percent/);
  assert.match(pageSource, /commitDemoState/);
  assert.match(pageSource, /closeOpenPositionByPercent/);
  assert.match(pageSource, /Manual close size percent/);
  assert.match(pageSource, /openDemoPosition/);
  assert.match(pageSource, /placeDemoLimitOrder/);
  assert.match(pageSource, /cancelDemoLimitOrder/);
  assert.match(pageSource, /demoState\.pendingLimitOrder/);
  assert.doesNotMatch(pageSource, /setPendingLimitOrder/);
  assert.match(pageSource, /updateDemoStopLoss/);
  assert.match(pageSource, /updateDemoTakeProfits/);
  assert.match(pageSource, /updateDemoLeverage/);
  assert.match(pageSource, /Close at Market/);
  assert.match(pageSource, /primary-button danger-button candle-hover-button manual-close-button/);
  assert.match(stylesSource, /manual-close-button[\s\S]*box-shadow: none/);
  assert.match(pageSource, /Export CSV/);
  assert.match(pageSource, /ghost-button compact candle-hover-button/);
  assert.match(pageSource, /DEMO_TRADE_HISTORY_PAGE_SIZE = 10/);
  assert.match(pageSource, /function getTradeHistoryPaginationItems/);
  assert.match(pageSource, /const paginatedTrades = useMemo/);
  assert.match(pageSource, /trades\.slice\(start, start \+ DEMO_TRADE_HISTORY_PAGE_SIZE\)/);
  assert.match(pageSource, /Trade history pages/);
  assert.match(pageSource, /aria-current=\{item === safePage \? "page" : undefined\}/);
  assert.match(stylesSource, /demo-history-panel \.section-heading \{[\s\S]*justify-content: space-between/);
  assert.match(stylesSource, /demo-history-pagination/);
  assert.match(stylesSource, /demo-history-pagination button\.active/);
  const performancePanelIndex = pageSource.indexOf("<PerformanceStats stats={stats} />");
  const balancePanelIndex = pageSource.indexOf('className="section-panel demo-balance-panel no-hover-effect"');
  assert.ok(performancePanelIndex !== -1 && balancePanelIndex !== -1 && performancePanelIndex < balancePanelIndex);
  assert.match(stylesSource, /demo-summary-grid \{[\s\S]*grid-template-columns: minmax\(0, 1\.75fr\) minmax\(300px, 0\.62fr\)/);
  assert.match(stylesSource, /demo-summary-grid \{[\s\S]*align-items: stretch/);
  assert.match(stylesSource, /demo-balance-panel \{[\s\S]*align-content: stretch/);
  assert.match(pageSource, /Clean reset/);
  assert.match(pageSource, /Your demo stats rebuild from the new starting balance/);
  assert.match(stylesSource, /demo-balance-copy/);
  assert.match(stylesSource, /demo-balance-note/);
  assert.match(pageSource, /Changing your starting demo balance will reset your current demo progress/);
  assert.match(pageSource, /Reset and Apply New Balance/);
});

test("BTC market data provider is isolated and uses public REST data", () => {
  assert.match(marketDataSource, /fetchDemoTradeCandles/);
  assert.match(marketDataSource, /fetchDemoTradeCandleResult/);
  assert.match(marketDataSource, /fetchDemoTradeMarketSnapshot/);
  assert.match(marketDataSource, /DEMO_TRADE_CHART_CANDLE_LIMIT = 720/);
  assert.match(marketDataSource, /demoTradeMaxCandleLimit = 1000/);
  assert.match(marketDataSource, /limit = DEMO_TRADE_CHART_CANDLE_LIMIT/);
  assert.match(marketDataSource, /candles\.slice\(-demoTradeMaxCandleLimit\)/);
  assert.match(marketDataSource, /fetchDemoTradeTicker/);
  assert.match(marketDataSource, /subscribeDemoTradePriceStream/);
  assert.match(marketDataSource, /WebSocket/);
  assert.match(marketDataSource, /@trade/);
  assert.match(marketDataSource, /DemoTradeTimeframe = "1m" \| "5m" \| "15m" \| "1h" \| "4h" \| "6h" \| "12h" \| "1d" \| "1w" \| "1M"/);
  assert.match(marketDataSource, /api\.binance\.us\/api\/v3/);
  assert.match(marketDataSource, /api\.binance\.com\/api\/v3/);
  assert.match(marketDataSource, /api\.exchange\.coinbase\.com/);
  assert.match(marketDataSource, /api\.coinbase\.com\/v2\/prices\/BTC-USD\/spot/);
  assert.match(marketDataSource, /demoTradeMarketCacheKey/);
  assert.match(marketDataSource, /readCachedTicker/);
  assert.match(marketDataSource, /readCachedCandles/);
  assert.match(marketDataSource, /function normalizeCandleBounds/);
  assert.match(marketDataSource, /high: Math\.max\(open, high, low, close\)/);
  assert.match(marketDataSource, /candle\.high >= Math\.max\(candle\.open, candle\.close\)/);
  assert.match(pageSource, /fetchDemoTradeMarketSnapshot/);
  assert.match(pageSource, /fetchDemoTradeCandleResult/);
  assert.match(pageSource, /Showing cached data while retrying/);
  assert.doesNotMatch(marketDataSource, /apiKey|secret|TradingView/);
});

test("registered demo state migration includes RLS and server-side validation", () => {
  assert.match(migrationSource, /create table if not exists public\.demo_trade_states/);
  assert.match(migrationSource, /enable row level security/);
  assert.match(migrationSource, /auth\.uid\(\) = user_id/);
  assert.match(migrationSource, /validate_demo_trade_state/);
  assert.match(migrationSource, /save_demo_trade_state/);
  assert.match(migrationSource, /BTCUSDT/);
  assert.match(grantMigrationSource, /grant select, insert, update on table public\.demo_trade_states to authenticated/);
  assert.match(grantMigrationSource, /grant execute on function public\.save_demo_trade_state\(jsonb\) to authenticated/);
  assert.match(grantMigrationSource, /notify pgrst, 'reload schema'/);
  assert.match(staleSaveMigrationSource, /demo_trade_state_updated_at/);
  assert.match(staleSaveMigrationSource, /public\.demo_trade_state_updated_at\(public\.demo_trade_states\.state\)/);
  assert.match(staleSaveMigrationSource, /<= incoming_updated_at/);
  assert.match(staleSaveMigrationSource, /notify pgrst, 'reload schema'/);
});
